### PR TITLE
Fix most of the compilation warnings

### LINKED ISSUE #223: Fix warnings about unused vars/params
```
[warn] /home/plipski/ide-probe/core/driver/test-plugin/src/main/scala/org/virtuslab/ideprobe/test/OpenWindowAction.scala:11:9: local val p in method actionPerformed is never used
[warn]     val p = e.getProject
[warn]         ^
[warn] one warning found
[info]   Compilation completed in 28.58s.
[warn] /home/plipski/ide-probe/core/driver/test-plugin/src/main/scala/org/virtuslab/ideprobe/test/OpenWindowAction.scala:11:9: local val p in method actionPerformed is never used
[warn]     val p = e.getProject
[warn]         ^
[warn] /home/plipski/ide-probe/core/api/src/main/scala/org/virtuslab/ideprobe/jsonrpc/JsonRpc.scala:72:42: parameter value evidence$1 in class Method is never used
[warn]   sealed abstract class Method[Parameters: ClassTag: ConfigConvert, Result: ClassTag: ConfigConvert] {
[warn]                                          ^
[warn] one warning found
[warn] /home/plipski/ide-probe/core/api/src/main/scala/org/virtuslab/ideprobe/jsonrpc/JsonRpcEndpoint.scala:19:17: parameter value evidence$1 in method sendRequest is never used
[warn]   protected def sendRequest[A: ClassTag, B: ClassTag](method: Method[A, B], parameters: A): Future[B] = {
[warn]                 ^
```

In fact, I'd elevate all warnings to errors (`-Xfatal-warnings`).

image

### PR DESCRIPTION
**Pull request by LukaszKontowski**
Closes #223

### CODE REVIEW

File: core/driver/sources/src/main/scala/org/virtuslab/ideprobe/Shell.scala [hunk 1]
```diff
@@ -172,5 +171,5 @@ class BaseShell {
     Seq(outputForwarder)
   }
 
-  protected def customizeBuilder(builder: NuProcessBuilder): Unit = ()
```
Comment (lukaszwawrzyk) [inline core/driver/sources/src/main/scala/org/virtuslab/ideprobe/Shell.scala:175]: how are inheritors supposed to customizeBuilder if you take away the builder?

File: core/driver/sources/src/main/scala/org/virtuslab/ideprobe/Shell.scala [hunk 2]
```diff
@@ -118,7 +117,7 @@ class BaseShell {
     import com.zaxxer.nuprocess._
     val builder = new NuProcessBuilder(command: _*)
     builder.setCwd(in)
-    customizeBuilder(builder)
+    customizeBuilder()
```
Comment (PawelLipski) [inline core/driver/sources/src/main/scala/org/virtuslab/ideprobe/Shell.scala:120]: :suspicious:

File: core/driver/sources/src/main/scala/org/virtuslab/ideprobe/Shell.scala [hunk 3]
```diff
@@ -172,5 +171,5 @@ class BaseShell {
     Seq(outputForwarder)
   }
 
-  protected def customizeBuilder(builder: NuProcessBuilder): Unit = ()
+  protected def customizeBuilder(): Unit = ()
```
Comment (PawelLipski) [inline core/driver/sources/src/main/scala/org/virtuslab/ideprobe/Shell.scala:174]: Oh! indeed, this looks like a method meant for extension

File: core/driver/sources/src/main/scala/org/virtuslab/ideprobe/dependencies/Resource.scala [hunk 4]
```diff
@@ -7,19 +7,19 @@ import java.nio.file.Files
...
 import org.virtuslab.ideprobe.Extensions._
 
+import scala.annotation.nowarn
+
 sealed trait Resource
 
 object Resource extends ConfigFormat {
   implicit val resourceConfigReader: ConfigReader[Resource] = ConfigReader[String].map(from)
 
+  @nowarn // as match is not exhaustive - case class Jar is not handled
```
Comment (PawelLipski) [inline core/driver/sources/src/main/scala/org/virtuslab/ideprobe/dependencies/Resource.scala:22]: Hmmm actually... maybe it should be handled here? 🤔 or if we know from somewhere else that Jar will never be passed here (doubt), then a separate trait should be extracted? pls open an issue (as I suppose it's not trivial enough to be fixed on this PR)

File: core/probePlugin/src/main/scala/org/virtuslab/ideprobe/handlers/ExpandMacro.scala [hunk 5]
```diff
@@ -30,7 +31,7 @@ object ExpandMacro {
     val data = new THashMap[String, Object]()
     data.put(CommonDataKeys.PROJECT.getName, fileRef.project)
     data.put(CommonDataKeys.VIRTUAL_FILE.getName, file)
-    data.put(PlatformDataKeys.PROJECT_FILE_DIRECTORY.getName, project.getBaseDir)
+    data.put(PlatformDataKeys.PROJECT_FILE_DIRECTORY.getName, ProjectUtil.guessProjectDir(project))
```
Comment (PawelLipski) [inline core/probePlugin/src/main/scala/org/virtuslab/ideprobe/handlers/ExpandMacro.scala:34]: Huh is this equivalent to `getBaseDir`? 🤔

Comment (PawelLipski) [reply core/probePlugin/src/main/scala/org/virtuslab/ideprobe/handlers/ExpandMacro.scala:34]: I suppose that was what the deprecation warning pointed to?

File: core/driver/sources/src/main/scala/org/virtuslab/ideprobe/Shell.scala (hunk 1 above)
Comment (LukaszKontowski) [reply core/driver/sources/src/main/scala/org/virtuslab/ideprobe/Shell.scala:175]: You're right - it would make no sense. I just did not find any implementation of this method in the source code and wanted to get rid of the warning

File: core/probePlugin/src/main/scala/org/virtuslab/ideprobe/handlers/IntelliJApi.scala [hunk 6]
```diff
@@ -81,13 +80,13 @@ trait IntelliJApi {
...
 
-    def field[B: ClassTag](name: String): B = {
+    def field[B](name: String): B = {
       val field = getField(obj.getClass, "my" + name.capitalize)
       using(field)(_.get(obj).asInstanceOf[B])
     }
 
     private def using[B <: AccessibleObject, C](accessible: B)(f: B => C): C = {
-      val isAccessible = accessible.isAccessible
+      val isAccessible = accessible.canAccess(null) // isAccessible
```
Comment (PawelLipski) [inline core/probePlugin/src/main/scala/org/virtuslab/ideprobe/handlers/IntelliJApi.scala:89]: Whoops deprecated?

Pls clarify in the comment what you mean by `isAccessible` (it won't be clear soon)

File: build.sbt [hunk 7]
```diff
@@ -312,7 +313,7 @@ lazy val benchmarks212 = benchmarks(scala212)
 def project(id: String, path: String, publish: Boolean): Project = {
   Project(id, sbt.file(path))
     .settings(scalafmtOnCompile := true)
-    .settings(scalacOptions ++= Seq("-Xlint:unused", "-Ywarn-unused"))
+    .settings(scalacOptions ++= Seq("-Xlint:unused", "-Ywarn-unused", "-deprecation", "-Ywarn-macros:after"))
```
Comment (PawelLipski) [inline build.sbt:316]: `-Xfatal-warnings` FTW

File: core/driver/sources/src/main/scala/org/virtuslab/ideprobe/Shell.scala (hunk 1 above)
Comment (PawelLipski) [reply core/driver/sources/src/main/scala/org/virtuslab/ideprobe/Shell.scala:175]: Huh the other problem might be that... will this builder ever be customized indeed? 😅 @lukaszwawrzyk was the customization added just in case?

File: core/probePlugin/src/main/scala/org/virtuslab/ideprobe/handlers/IntelliJApi.scala (hunk 6 above)
Comment (LukaszKontowski) [reply core/probePlugin/src/main/scala/org/virtuslab/ideprobe/handlers/IntelliJApi.scala:89]: just forgot to remove the `// isAccessible` - will do that in next commit. `isAccessible` is deprecated. Moreover, I will have to double check if `canAccess(null)` should be used - or `canAccess(obj: Object)` with some real object... I am not sure yet after quick read of the source code of this method.

File: core/probePlugin/src/main/scala/org/virtuslab/ideprobe/handlers/ExpandMacro.scala (hunk 5 above)
Comment (LukaszKontowski) [reply core/probePlugin/src/main/scala/org/virtuslab/ideprobe/handlers/ExpandMacro.scala:34]: It should be, if I get the javadoc in source code right...
```
/**
 *  Tries to guess the "main project directory" of the project.
 *
 *  There is no strict definition of what is a project directory, since a project can contain multiple modules located in different places,
 *  and the `.idea` directory can be located elsewhere (making the popular [Project.getBaseDir] method not applicable to get the "project
 *  directory"). This method should be preferred, although it can't provide perfect accuracy either.
 */
fun Project.guessProjectDir() : VirtualFile? {
  if (isDefault) {
    return null
  }

  val modules = ModuleManager.getInstance(this).modules
  val module = if (modules.size == 1) modules.first() else modules.firstOrNull { it.name == this.name }
  module?.guessModuleDir()?.let { return it }
  return LocalFileSystem.getInstance().findFileByPath(basePath!!)
}
```

Comment (PawelLipski) [reply core/probePlugin/src/main/scala/org/virtuslab/ideprobe/handlers/ExpandMacro.scala:34]: Actually, it's [KDoc](https://kotlinlang.org/docs/kotlin-doc.html) in this case ;)

Comment (PawelLipski) [reply core/probePlugin/src/main/scala/org/virtuslab/ideprobe/handlers/ExpandMacro.scala:34]: But javadoc/KDoc/scaladoc are barely distinguishable from each other, save for what language they're used in

File: build.sbt (hunk 7 above)
Comment (LukaszKontowski) [reply build.sbt:316]: Ok, if I would be able to get rid of all warnings, then I will add this flag

File: core/driver/sources/src/main/scala/org/virtuslab/ideprobe/dependencies/Resource.scala (hunk 4 above)
Comment (LukaszKontowski) [reply core/driver/sources/src/main/scala/org/virtuslab/ideprobe/dependencies/Resource.scala:22]: Issue created: https://github.com/VirtusLab/ide-probe/issues/242 - until the issue is done, I suggest to have this `@nowarn` annotation added.

File: build.sbt (hunk 7 above)
Comment (LukaszKontowski) [reply build.sbt]: For now, I cannot add this flag, due to https://github.com/VirtusLab/ide-probe/issues/243

File: core/driver/test-plugin/src/main/scala/org/virtuslab/ideprobe/test/OpenWindowAction.scala [hunk 8]
```diff
@@ -8,6 +8,7 @@ import javax.swing.Icon
 
 class OpenWindowAction extends AnAction("Open Window") with DumbAware {
   override def actionPerformed(e: AnActionEvent): Unit = {
+    val p = e.getProject
```
Comment (PawelLipski) [inline core/driver/test-plugin/src/main/scala/org/virtuslab/ideprobe/test/OpenWindowAction.scala:11]: Huh I'd be really surprised if that was the reason 😯

Comment (LukaszKontowski) [reply core/driver/test-plugin/src/main/scala/org/virtuslab/ideprobe/test/OpenWindowAction.scala:11]: Yeah, but test failures are so confusing that I want to try something. Looks like something from my changes is the reason, as these tests were successful on previous PR today https://github.com/VirtusLab/ide-probe/pull/240
(still, I have tha same failures for tests locally on **master** branch, but maybe this is some other reason for this)

File: core/probePlugin/src/main/scala/org/virtuslab/ideprobe/handlers/IntelliJApi.scala (hunk 6 above)
Comment (LukaszKontowski) [reply core/probePlugin/src/main/scala/org/virtuslab/ideprobe/handlers/IntelliJApi.scala]: Looks like we would have to stick to the `isAccessible` for now. Proper replacement with `canAccess` is not that obvious. Issue https://github.com/VirtusLab/ide-probe/issues/244 created.

**Comment by LukaszKontowski** [comment]
Issues created as a result of working on this PR:
https://github.com/VirtusLab/ide-probe/issues/242
https://github.com/VirtusLab/ide-probe/issues/243
https://github.com/VirtusLab/ide-probe/issues/244

**Review by PawelLipski — APPROVED** [review]

File: core/probePlugin/src/main/scala/org/virtuslab/ideprobe/handlers/Builds.scala [hunk 9]
```diff
@@ -109,7 +109,7 @@ object Builds extends IntelliJApi {
         compileContext: CompileContext
     ): Unit = {
       def messages(category: CompilerMessageCategory): Seq[BuildMessage] = {
-        compileContext.getMessages(category).map { msg =>
+        compileContext.getMessages(category).toIndexedSeq.map { msg =>
```
Comment (lukaszwawrzyk) [inline core/probePlugin/src/main/scala/org/virtuslab/ideprobe/handlers/Builds.scala:112]: why this toIndexedSeq conversion happens everywhere?

Comment (LukaszKontowski) [reply core/probePlugin/src/main/scala/org/virtuslab/ideprobe/handlers/Builds.scala:112]: Without it (as we have on master now) - we are having following warnings (which contain answer, **why**):
```
[warn] /Users/lkontowski/code/ide-probe/core/probePlugin/src/main/scala/org/virtuslab/ideprobe/handlers/Builds.scala:112:50: method copyArrayToImmutableIndexedSeq in class LowPriorityImplicits2 is deprecated (since 2.13.0): Implicit conversions from Array to immutable.IndexedSeq are implemented by copying; Use the more efficient non-copying ArraySeq.unsafeWrapArray or an explicit toIndexedSeq call
[warn]         compileContext.getMessages(category).map { msg =>
[warn]                                                  ^
[warn] one warning found
```
