### PR TITLE
fixed JbrResolvers pattern resolving logic

### LINKED ISSUE #213: As of 2022.2 EAPs, `jbr_dcevm` seems no longer available; consider `jbr_jcef` or even just `jbr`
To run tests against 2022.2 EAP, I need to [patch `probe.resolvers.jbr.repositories`](https://github.com/VirtusLab/git-machete-intellij-plugin/pull/959/files):

```
    jbr.repositories = [
      # As of ide-probe v0.34.0, this is the `official`/default resolver (see `org.virtuslab.ideprobe.dependencies.JbrResolvers.official`).
      # Let's state the URL explicitly here anyway.
      # For further details on DCEVM (Dynamic Code Evolution VM), see https://blog.jetbrains.com/idea/2013/07/get-true-hot-swap-in-java-with-dcevm-and-intellij-idea/
      "https://cache-redirector.jetbrains.com/intellij-jbr/jbr_dcevm-[major]-[platform]-x64-b[minor].tar.gz",
 
     # As of Intellij 2022.2, jbr_dcevm seems no longer available for some reason.
      # Let's use jbr_jcef instead.
      # For further details on JCEF (Java Chromium Embedded Framework), see https://plugins.jetbrains.com/docs/intellij/jcef.html
      "https://cache-redirector.jetbrains.com/intellij-jbr/jbr_jcef-[major]-[platform]-x64-b[minor].tar.gz"
    ]
```

Maybe `jbr_jcef` JBRs were also available for the earlier versions and could be made the sole `official`/default one?
Or alternatively, both `jbr_dcevm` and `jbr_jcef` could be included as defaults.

### LINKED ISSUE #255: Add support for `aarch64` in default jbr-related configurations
Currently, default configurations have `x64` hardcoded as the only supported architecture.

### PR DESCRIPTION
**Pull request by LukaszKontowski**
Closes #213

### CODE REVIEW

File: core/driver/sources/src/main/scala/org/virtuslab/ideprobe/dependencies/JbrResolvers.scala [hunk 1]
```diff
@@ -11,19 +11,22 @@ import org.virtuslab.ideprobe.dependencies.Dependency.Missing
 import org.virtuslab.ideprobe.Extensions.PathExtension
 
 object JbrResolvers {
-  val official =
-    JbrPatternResolver(
-      "https://cache-redirector.jetbrains.com/intellij-jbr/jbr_dcevm-[major]-[platform]-x64-b[minor].tar.gz"
-    )
+  // The `jbr_dcevm` pattern applies only to versions of IntelliJ older than 2022.2 release, whereas
+  // `jbr` pattern applies to newer versions and has dcevm bundled by default.
+  private val officialJbrVersionPatterns = Seq(
```
Comment (PawelLipski) [inline core/driver/sources/src/main/scala/org/virtuslab/ideprobe/dependencies/JbrResolvers.scala:16]: Pls open a PR in git-machete-intellij-plugin that would use this piece in ideprobe.conf... in CircleCI config, use:

```yaml
name: Install sbt
# language=sh
command: |
  apt update
  apt-get install apt-transport-https gnupg -yqq
  echo "deb https://repo.scala-sbt.org/scalasbt/debian all main" | tee /etc/apt/sources.list.d/sbt.list
  echo "deb https://repo.scala-sbt.org/scalasbt/debian /" | tee /etc/apt/sources.list.d/sbt_old.list
  curl -sL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823" | gpg --no-default-keyring --keyring gnupg-ring:/etc/apt/trusted.gpg.d/scalasbt-release.gpg --import
  chmod 644 /etc/apt/trusted.gpg.d/scalasbt-release.gpg
  apt-get update
  apt-get install sbt
```

and

```yaml
- run:
    name: Build ide-probe fork
    # language=sh
    command: |
      cd ..
      git clone https://github.com/azdrojowa123/ide-probe.git -b fix/jbr_installation_directory
      cd ide-probe/
      sbt api_2_13/publishM2 driver_2_13/publishM2 junit-driver_2_13/publishM2 robot-driver_2_13/publishM2 probe-plugin_2_13/publishM2
```

File: core/driver/sources/src/main/scala/org/virtuslab/ideprobe/dependencies/JbrResolvers.scala [hunk 2]
```diff
@@ -11,19 +11,22 @@ import org.virtuslab.ideprobe.dependencies.Dependency.Missing
 import org.virtuslab.ideprobe.Extensions.PathExtension
 
 object JbrResolvers {
-  val official =
-    JbrPatternResolver(
-      "https://cache-redirector.jetbrains.com/intellij-jbr/jbr_dcevm-[major]-[platform]-x64-b[minor].tar.gz"
-    )
+  // The `jbr_dcevm` pattern applies only to versions of IntelliJ older than 2022.2 release, whereas
+  // `jbr` pattern applies to newer versions and has dcevm bundled by default.
```
Comment (PawelLipski) [inline core/driver/sources/src/main/scala/org/virtuslab/ideprobe/dependencies/JbrResolvers.scala:15]:
```suggestion
  // `jbr` pattern applies to newer versions where DCEVM is bundled by default.
```

File: core/driver/sources/src/main/scala/org/virtuslab/ideprobe/dependencies/JbrResolvers.scala (hunk 1 above)
Comment (LukaszKontowski) [reply core/driver/sources/src/main/scala/org/virtuslab/ideprobe/dependencies/JbrResolvers.scala:16]: Ok, but I still do not understand fully - after running
`sbt api_2_13/publishM2 driver_2_13/publishM2 junit-driver_2_13/publishM2 robot-driver_2_13/publishM2 probe-plugin_2_13/publishM2`
We have to additionally:
- `grep` published `SNAPSHOT` version number
and
- replace official release in `gradle/libs.versions.toml`
So these two steps have to be created in `.circleci.config.yml` right? And this whole Pull Request would be just for a temporary test - will not be merged? 
Maybe you can just let me know, if there was such a PR in the past and add a link to it? I did not manage to find an example PR unfortunately.

**Comment by LukaszKontowski** [comment]
It shows up that using the `aarch64` JBR package instead of `x64` on the Mac with "aarch64" architecture causes following error when testing with `git-machete-intellij-plugin`:
```
[intellij-stderr] 2022-08-20 13:54:39.652 idea[2718:43604] Cannot load JVM bundle: Error Domain=NSCocoaErrorDomain Code=3585 "dlopen_preflight(/var/folders/6j/141ys4_178d0r360cfsvg7g40000gn/T/ide-probe/instances/intellij-instance-2022.2.1--E4WAFnXGQfeorN1-AHCx-A/Contents/jbr/Contents/MacOS/libjli.dylib) => false, 'tried: '/var/folders/6j/141ys4_178d0r360cfsvg7g40000gn/T/ide-probe/instances/intellij-instance-2022.2.1--E4WAFnXGQfeorN1-AHCx-A/Contents/jbr/Contents/MacOS/libjli.dylib' (mach-o file, but is an incompatible architecture (have (arm64), need (x86_64))), '/usr/local/lib/libjli.dylib' (no such file), '/usr/lib/libjli.dylib' (no such file)'" UserInfo={NSLocalizedFailureReason=The bundle doesn’t contain a version for the current architecture., NSLocalizedRecoverySuggestion=Try installing a universal version of the bundle., NSFilePath=/var/folders/6j/141ys4_178d0r360cfsvg7g40000gn/T/ide-probe/instances/intellij-instance-2022.2.1--E4WAFnXGQfeorN1-AHCx-A/Contents/jbr/Contents/MacOS/libjli.dylib, NSDebugDescription=dlopen_preflight(/var/folders/6j/141ys4_178d0r360cfsvg7g40000gn/T/ide-probe/instances/intellij-instance-2022.2.1--E4WAFnXGQfeorN1-AHCx-A/Contents/jbr/Contents/MacOS/libjli.dylib) => false, 'tried: '/var/folders/6j/141ys4_178d0r360cfsvg7g40000gn/T/ide-probe/instances/intellij-instance-2022.2.1--E4WAFnXGQfeorN1-AHCx-A/Contents/jbr/Contents/MacOS/libjli.dylib' (mach-o file, but is an incompatible architecture (have (arm64), need (x86_64))), '/usr/local/lib/libjli.dylib' (no such file), '/usr/lib/libjli.dylib' (no such file)', NSBundlePath=/var/folders/6j/141ys4_178d0r360cfsvg7g40000gn/T/ide-probe/instances/intellij-instance-2022.2.1--E4WAFnXGQfeorN1-AHCx-A/Contents/jbr, NSLocalizedDescription=The bundle “JBR-17.0.3+7-469.37-nomod 17.0.3” couldn’t be loaded because it doesn’t contain a version for the current architecture.}
```
I'm checking the cause for such strange failure

File: core/driver/sources/src/main/scala/org/virtuslab/ideprobe/dependencies/JbrResolvers.scala (hunk 1 above)
Comment (PawelLipski) [reply core/driver/sources/src/main/scala/org/virtuslab/ideprobe/dependencies/JbrResolvers.scala:16]: > replace official release with new snapshot version in gradle/libs.versions.toml

This is to be done manually by the developer on the PR itself... as they will already know the exact version of ide-probe to use.

> And this whole Pull Request would be just for a temporary test - will not be merged?

Yeah, we generally only want to merge the PR once ide-probe is released... and then use a regular (non-snapshot) ide-probe version. Or rather, this can indeed be a new PR, where ideprobe.conf is adequately updated, and ide-probe version bumped to the released one.

> Maybe you can just let me know, if there was such a PR in the past and add a link to it? I did not manage to find an example PR unfortunately.

Lemme find such commit from reflogs and push as a branch...

Comment (PawelLipski) [reply core/driver/sources/src/main/scala/org/virtuslab/ideprobe/dependencies/JbrResolvers.scala:16]: Okay, just check the commit (`f9ac2f5dc131b2a492a3225be1c58d79758c7baf`) pointed by `demo/ide-probe-snapshot` branch in git-machete-intellij-plugin... that's basically just changes to CircleCI config + ide-probe version change in the TOML catalog

File: core/driver/sources/src/main/scala/org/virtuslab/ideprobe/dependencies/JbrResolvers.scala [hunk 3]
```diff
@@ -11,19 +11,22 @@ import org.virtuslab.ideprobe.dependencies.Dependency.Missing
...
 object JbrResolvers {
-  val official =
-    JbrPatternResolver(
-      "https://cache-redirector.jetbrains.com/intellij-jbr/jbr_dcevm-[major]-[platform]-x64-b[minor].tar.gz"
-    )
+  // The `jbr_dcevm` pattern applies only to versions of IntelliJ older than 2022.2 release, whereas
+  // `jbr` pattern applies to newer versions where DCEVM is bundled by default.
+  private val officialJbrVersionPatterns = Seq(
+    "https://cache-redirector.jetbrains.com/intellij-jbr/jbr_dcevm-[major]-[platform]-[architecture]-b[minor].tar.gz",
+    "https://cache-redirector.jetbrains.com/intellij-jbr/jbr-[major]-[platform]-[architecture]-b[minor].tar.gz"
```
Comment (PawelLipski) [inline core/driver/sources/src/main/scala/org/virtuslab/ideprobe/dependencies/JbrResolvers.scala:18]: Hmmm where is gonna the value for `architecture` be provided from now? 🤔

Comment (PawelLipski) [reply core/driver/sources/src/main/scala/org/virtuslab/ideprobe/dependencies/JbrResolvers.scala:18]: As `JbrPatternResolver#resolve` doesn't know about that anymore

Comment (LukaszKontowski) [reply core/driver/sources/src/main/scala/org/virtuslab/ideprobe/dependencies/JbrResolvers.scala:18]: OK, forgot to switch back from `[architecture]` to `x64` - let me fix

File: core/driver/sources/src/main/scala/org/virtuslab/ideprobe/dependencies/JbrResolvers.scala [hunk 4]
```diff
@@ -11,19 +11,22 @@ import org.virtuslab.ideprobe.dependencies.Dependency.Missing
...
 object JbrResolvers {
-  val official =
-    JbrPatternResolver(
-      "https://cache-redirector.jetbrains.com/intellij-jbr/jbr_dcevm-[major]-[platform]-x64-b[minor].tar.gz"
-    )
+  // The `jbr_dcevm` pattern applies only to versions of IntelliJ older than 2022.2 release, whereas
+  // `jbr` pattern applies to newer versions where DCEVM is bundled by default.
+  private val officialJbrVersionPatterns = Seq(
+    "https://cache-redirector.jetbrains.com/intellij-jbr/jbr_dcevm-[major]-[platform]-x64-b[minor].tar.gz",
+    "https://cache-redirector.jetbrains.com/intellij-jbr/jbr-[major]-[platform]-x64-b[minor].tar.gz"
```
Comment (PawelLipski) [inline core/driver/sources/src/main/scala/org/virtuslab/ideprobe/dependencies/JbrResolvers.scala:18]: Actually, you can add a comment here why `aarch64` isn't a good idea

File: core/driver/sources/src/main/scala/org/virtuslab/ideprobe/dependencies/JbrResolvers.scala (hunk 3 above)
Comment (LukaszKontowski) [reply core/driver/sources/src/main/scala/org/virtuslab/ideprobe/dependencies/JbrResolvers.scala]: done 👍

File: core/driver/sources/src/main/scala/org/virtuslab/ideprobe/dependencies/JbrResolvers.scala [hunk 5]
```diff
@@ -11,8 +11,14 @@ import org.virtuslab.ideprobe.dependencies.Dependency.Missing
 import org.virtuslab.ideprobe.Extensions.PathExtension
 
 object JbrResolvers {
-  // The `jbr_dcevm` pattern applies only to versions of IntelliJ older than 2022.2 release, whereas
-  // `jbr` pattern applies to newer versions where DCEVM is bundled by default.
+  /*
+  The `jbr_dcevm` pattern applies only to versions of IntelliJ older than 2022.2 release, whereas
+  `jbr` pattern applies to newer versions where DCEVM is bundled by default.
+  Another important note: currently we are using only JBR packages with `x64` architecture support. During tests
+  it showed up that using `aarch64` packages on processors with `aarch64` architecture (Mac M1 Pro chip) results
```
Comment (PawelLipski) [inline core/driver/sources/src/main/scala/org/virtuslab/ideprobe/dependencies/JbrResolvers.scala:18]:
```suggestion
  it turned out that using `aarch64` packages on processors with `aarch64` architecture (Mac M1 Pro chip) results
```

**Review by PawelLipski — APPROVED** [review]

File: core/driver/sources/src/main/scala/org/virtuslab/ideprobe/dependencies/JbrResolvers.scala (hunk 1 above)
Comment (LukaszKontowski) [reply core/driver/sources/src/main/scala/org/virtuslab/ideprobe/dependencies/JbrResolvers.scala:22]: Success: https://github.com/VirtusLab/git-machete-intellij-plugin/pull/1080

**Review by lukaszwawrzyk — APPROVED** [review]

File: core/driver/sources/src/main/scala/org/virtuslab/ideprobe/dependencies/JbrResolvers.scala [hunk 6]
```diff
@@ -11,19 +11,28 @@ import org.virtuslab.ideprobe.dependencies.Dependency.Missing
...
+  it turned out that using `aarch64` packages on processors with `aarch64` architecture (Mac M1 Pro chip) results
+  in "Cannot load JVM bundle:" error. For some reason only `x64` packages work well (both for `x64` and `aarch64`
+  processor architectures). Hence `x64` should stay hardcoded in the `officialJbrVersionPatterns` elements.
+   */
+  private val officialJbrVersionPatterns = Seq(
+    "https://cache-redirector.jetbrains.com/intellij-jbr/jbr_dcevm-[major]-[platform]-x64-b[minor].tar.gz",
+    "https://cache-redirector.jetbrains.com/intellij-jbr/jbr-[major]-[platform]-x64-b[minor].tar.gz"
+  )
+
+  val officialResolvers: Seq[JbrPatternResolver] = officialJbrVersionPatterns.map(JbrPatternResolver)
```
Comment (lukaszwawrzyk) [inline core/driver/sources/src/main/scala/org/virtuslab/ideprobe/dependencies/JbrResolvers.scala:27]: I would still just call it `official` for consistency. And public API is `JbrResolvers.official` which doesn't duplicate the `resolvers` part

**Review by lukaszwawrzyk — APPROVED** [review]

**Comment by PawelLipski** [comment]
Friday... let's make a release!

File: core/driver/sources/src/main/scala/org/virtuslab/ideprobe/dependencies/JbrResolvers.scala (hunk 6 above)
Comment (LukaszKontowski) [reply core/driver/sources/src/main/scala/org/virtuslab/ideprobe/dependencies/JbrResolvers.scala]: Done
