### PR TITLE
Fix IntelliJVersionResolver.version logic for macOs

### LINKED ISSUE #271: Fix `IntelliJVersionResolver.version` method logic for osx
Currently in the `def version(intelliJPath: Path): IntelliJVersion` method, we have:
`val productInfo = intelliJPath.resolve("product-info.json").content()`

However, in case of IntelliJ IDEA installed on osx (macOs) - the `product-info.json` file is **NOT** placed directly under the `intelliJPath`. It is placed under `intelliJPath/Resources`. Example from my own installed IntelliJ:
```
lkontowski@lkontowski-MacBook-Pro /Users/lkontowski 
% ls -1 /Applications/IntelliJ\ IDEA\ CE.app/Contents/
CodeResources
Info.plist
MacOS
Resources
_CodeSignature
bin
jbr
lib
license
plugins

lkontowski@lkontowski-MacBook-Pro /Users/lkontowski 
% ls -1 /Applications/IntelliJ\ IDEA\ CE.app/Contents/Resources 
LICENSE.txt
NOTICE.txt
build.txt
idea.icns
product-info.json
```

### PR DESCRIPTION
**Pull request by LukaszKontowski**
Closes #271

### CODE REVIEW

File: core/driver/sources/src/main/scala/org/virtuslab/ideprobe/dependencies/IntelliJVersionResolver.scala [hunk 1]
```diff
@@ -5,10 +5,15 @@ import java.nio.file.Path
...
 
 import org.virtuslab.ideprobe.Extensions._
+import org.virtuslab.ideprobe.OS
 
 object IntelliJVersionResolver {
   def version(intelliJPath: Path): IntelliJVersion = {
-    val productInfo = intelliJPath.resolve("product-info.json").content()
+    val productInfo =
+      if (OS.Current == OS.Mac && intelliJPath.name == "Contents")
+        intelliJPath.resolve("Resources").resolve("product-info.json").content()
```
Comment (PawelLipski) [inline core/driver/sources/src/main/scala/org/virtuslab/ideprobe/dependencies/IntelliJVersionResolver.scala:14]: Wow the amount of differences b/w Mac OS and Linux distributions of IntelliJs is surprising...

Comment (LukaszKontowski) [reply core/driver/sources/src/main/scala/org/virtuslab/ideprobe/dependencies/IntelliJVersionResolver.scala:14]: yeah... Can't wait for adding Windows support here ^^

Comment (PawelLipski) [reply core/driver/sources/src/main/scala/org/virtuslab/ideprobe/dependencies/IntelliJVersionResolver.scala:14]: No way :trollface:

**Review by lukaszwawrzyk — APPROVED** [review]
