### PR TITLE
Performing cleanup even after IDE fails to start

### LINKED ISSUE #133: SingleRunIntelliJ does not perform cleanup if starting the IDE fails.
If for some reason the `idea.sh` file is missing, or has incorrect permissions, or simply fails to execute, the IDE's instance directory and its workspace don't get deleted.

### PR DESCRIPTION
**Pull request by kszydlo-vl**
Closes #133

### CODE REVIEW

File: core/driver/sources/src/test/scala/org/virtuslab/ideprobe/dependencies/SingleRunFixtureTest.scala [hunk 1]
```diff
@@ -49,4 +49,40 @@ final class SingleRunFixtureTest extends IdeProbeFixture with WorkspaceFixture w
...
+  @Test
+  def removesDirectoriesEvenAfterFailureToRunIntelliJ(): Unit = {
+    val intelliJFixture = IntelliJFixture(
+      version = IntelliJVersion.Latest,
+      plugins = List()
+    ).withAfterIntelliJInstall((_, intellij) =>
+      Files.delete(intellij.root.resolve("bin").resolve("idea.sh")) //To prevent the IDE from launching.
+    )
+
+    val instancesBefore = Option(intelliJFixture.factory.paths.instances.toFile.list().toSet).getOrElse(Set.empty)
```
Comment (lukaszwawrzyk) [inline core/driver/sources/src/test/scala/org/virtuslab/ideprobe/dependencies/SingleRunFixtureTest.scala:62]: It would be good to have some helper method for these 4 long chains of calls in this test.
There should be PathExtension util for listing files/directories, if not, it would be good to add. 
Also, why Option? How could `toSet` return null?

Comment (kszydlo-vl) [reply core/driver/sources/src/test/scala/org/virtuslab/ideprobe/dependencies/SingleRunFixtureTest.scala]: Indeed there is a PathExtension method for that. Using it now.

The Option here was to avoid getting NPE, since `File.list` method can return null - but I misplaced the `toSet` call. Anyway, it's probably unnecessary as the directories should be created at this point.

**Comment by lukaszwawrzyk** [comment]
Good to merge after resolving conflicts
